name: Launch GitBook deploy workflow

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-deploy:
    name: Trigger GitBook deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy workflow in obsidian-gitbook fork
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOY_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ant-lab-ru',
              repo: 'ant-mcu-gitbook',
              workflow_id: 'build-gitbook.yml',
              ref: 'main',
              inputs: {
                repo: '${{ github.repository }}',
              },
            });
